name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        version: 'latest'
    
    - name: Authenticate with gcloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sample --port 8080 --allow-unauthenticated --region us-central1 --source .

