name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sample --port 8080 --allow-unauthenticated --region us-central1 --source .

