name: 'Continuous Integration'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Install Make
      run: sudo apt-get install make
    
    - name: Create virtual environment and install dependencies
      run: |
        make venv
        source .venv/bin/activate
        make install

    - name: Install additional requirements
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Install Flask
      run: |
        source .venv/bin/activate
        pip install Flask==2.2.2
    
    - name: Run model tests
      run: |
        source .venv/bin/activate
        make model-test
    
    - name: Run API tests
      run: |
        source .venv/bin/activate
        make api-test
